tasks:
  - init: npm install
    command: npm run serve
    # command: node ./node_modules/NeteaseCloudMusicApi/app.js
# Ports to expose on workspace startup (optional)
ports:
  - port: 8080
    onOpen: open-preview
